services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:17-0.106.0-ferretdb-2.5.0
    restart: on-failure
    environment:
      - POSTGRES_USER=tipko
      - POSTGRES_PASSWORD=tipkopass
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2.5.0
    restart: on-failure
    depends_on:
      - postgres
    environment:
      - FERRETDB_AUTH=false
      - FERRETDB_POSTGRESQL_URL=postgres://tipko:tipkopass@postgres:5432/postgres

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tipko-backend
    restart: unless-stopped
    depends_on:
      - ferretdb
    ports:
      - "5186:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: "mongodb://ferretdb:27017/tipko"
      JWT_SECRET: "${JWT_SECRET}"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
